#!/bin/bash

# Welcome massage
echo "Welcome to Auburn's Annual Hey Day!"

# Prompt the user to enter their name

read -p "what's your name, tiger? " name

# Output a personalized greeting
echo "Hey $name! Have an amazing Hey Day at Auburn! War Eagle!"
